{"time":"2024-12-24T12:20:14.9470095+02:00","level":"INFO","msg":"using version","core version":"0.19.0"}
{"time":"2024-12-24T12:20:14.9476155+02:00","level":"INFO","msg":"created symlink","path":"C:\\Users\\User\\Documents\\herbskeeper\\HerbKeeper\\wandb\\run-20241224_122014-Herb_Keeper 400\\logs\\debug-core.log"}
{"time":"2024-12-24T12:20:15.0810266+02:00","level":"INFO","msg":"created new stream","id":"Herb_Keeper 400"}
{"time":"2024-12-24T12:20:15.081547+02:00","level":"INFO","msg":"stream: started","id":"Herb_Keeper 400"}
{"time":"2024-12-24T12:20:15.0823097+02:00","level":"INFO","msg":"writer: Do: started","stream_id":"Herb_Keeper 400"}
{"time":"2024-12-24T12:20:15.0828317+02:00","level":"INFO","msg":"sender: started","stream_id":"Herb_Keeper 400"}
{"time":"2024-12-24T12:20:15.0828317+02:00","level":"INFO","msg":"handler: started","stream_id":"Herb_Keeper 400"}
{"time":"2024-12-24T12:20:15.4575288+02:00","level":"INFO","msg":"Starting system monitor"}
{"time":"2024-12-24T12:24:19.9347496+02:00","level":"INFO","msg":"api: retrying error","error":"Post \"https://api.wandb.ai/graphql\": read tcp 192.168.245.216:59163->35.186.228.49:443: wsarecv: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond."}
{"time":"2024-12-24T12:24:22.1794943+02:00","level":"INFO","msg":"api: retrying error","error":"Post \"https://api.wandb.ai/files/shayfarjoon0-parkhamada/Herb_Keeper/Herb_Keeper%20400/file_stream\": dial tcp 35.186.228.49:443: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond."}
