cuda:0
cuda:0
Traceback (most recent call last):
  File "c:\Users\Farjoon\Documents\HerbsKeeper\HerbKeeper\DQN_trainer2.py", line 238, in <module>
    main()
  File "c:\Users\Farjoon\Documents\HerbsKeeper\HerbKeeper\DQN_trainer2.py", line 194, in main
    Q_values = player.DQN(states,actions)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\Farjoon\Documents\HerbsKeeper\HerbKeeper\DQN.py", line 64, in __call__
    return self.forward(states,actions).to(self.device)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\Farjoon\Documents\HerbsKeeper\HerbKeeper\DQN.py", line 37, in forward
    x = self.linear1(x)
        ^^^^^^^^^^^^^^^
  File "C:\Users\Farjoon\AppData\Local\Programs\Python\Python311\Lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Farjoon\AppData\Local\Programs\Python\Python311\Lib\site-packages\torch\nn\modules\linear.py", line 114, in forward
    return F.linear(input, self.weight, self.bias)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cpu and cuda:0! (when checking argument for argument mat1 in method wrapper_CUDA_addmm)
