{"time":"2024-12-24T12:58:31.0831386+02:00","level":"INFO","msg":"using version","core version":"0.19.0"}
{"time":"2024-12-24T12:58:31.0837139+02:00","level":"INFO","msg":"created symlink","path":"C:\\Users\\User\\Documents\\herbskeeper\\HerbKeeper\\wandb\\run-20241224_125831-Herb_Keeper 400\\logs\\debug-core.log"}
{"time":"2024-12-24T12:58:31.2259988+02:00","level":"INFO","msg":"created new stream","id":"Herb_Keeper 400"}
{"time":"2024-12-24T12:58:31.2265797+02:00","level":"INFO","msg":"stream: started","id":"Herb_Keeper 400"}
{"time":"2024-12-24T12:58:31.2265797+02:00","level":"INFO","msg":"writer: Do: started","stream_id":"Herb_Keeper 400"}
{"time":"2024-12-24T12:58:31.2265797+02:00","level":"INFO","msg":"sender: started","stream_id":"Herb_Keeper 400"}
{"time":"2024-12-24T12:58:31.2265797+02:00","level":"INFO","msg":"handler: started","stream_id":"Herb_Keeper 400"}
{"time":"2024-12-24T12:58:31.6139582+02:00","level":"INFO","msg":"Starting system monitor"}
{"time":"2024-12-24T13:00:21.0022074+02:00","level":"INFO","msg":"api: retrying error","error":"Post \"https://api.wandb.ai/graphql\": read tcp 192.168.245.216:56000->35.186.228.49:443: wsarecv: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond."}
{"time":"2024-12-24T13:00:23.3289023+02:00","level":"INFO","msg":"api: retrying error","error":"Post \"https://api.wandb.ai/files/shayfarjoon0-parkhamada/Herb_Keeper/Herb_Keeper%20400/file_stream\": dial tcp 35.186.228.49:443: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond."}
{"time":"2024-12-24T13:00:44.4698094+02:00","level":"INFO","msg":"api: retrying error","error":"Post \"https://api.wandb.ai/graphql\": dial tcp 35.186.228.49:443: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond."}
{"time":"2024-12-24T13:00:46.580919+02:00","level":"INFO","msg":"api: retrying error","error":"Post \"https://api.wandb.ai/files/shayfarjoon0-parkhamada/Herb_Keeper/Herb_Keeper%20400/file_stream\": dial tcp 35.186.228.49:443: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond."}
{"time":"2024-12-24T13:00:59.7988+02:00","level":"INFO","msg":"api: retrying error","error":"Post \"https://api.wandb.ai/graphql\": dial tcp: lookup api.wandb.ai: no such host"}
{"time":"2024-12-24T13:00:59.7988+02:00","level":"INFO","msg":"api: retrying error","error":"Post \"https://api.wandb.ai/files/shayfarjoon0-parkhamada/Herb_Keeper/Herb_Keeper%20400/file_stream\": dial tcp: lookup api.wandb.ai: no such host"}
{"time":"2024-12-24T13:01:20.6023797+02:00","level":"INFO","msg":"api: retrying error","error":"Post \"https://api.wandb.ai/files/shayfarjoon0-parkhamada/Herb_Keeper/Herb_Keeper%20400/file_stream\": dial tcp: lookup api.wandb.ai: no such host"}
{"time":"2024-12-24T13:01:20.6023797+02:00","level":"INFO","msg":"api: retrying error","error":"Post \"https://api.wandb.ai/graphql\": dial tcp: lookup api.wandb.ai: no such host"}
{"time":"2024-12-24T13:01:38.652122+02:00","level":"INFO","msg":"api: retrying error","error":"Post \"https://api.wandb.ai/files/shayfarjoon0-parkhamada/Herb_Keeper/Herb_Keeper%20400/file_stream\": dial tcp: lookup api.wandb.ai: no such host"}
{"time":"2024-12-24T13:01:40.089017+02:00","level":"INFO","msg":"api: retrying error","error":"Post \"https://api.wandb.ai/graphql\": dial tcp: lookup api.wandb.ai: no such host"}
